version: '3.3'
services:
  docker-mysql:
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_DATABASE: 'RHBASSESSTMENT'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'app'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Password123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted